### ISSUE TITLE
Split up "application_settings" ?

### ISSUE THREAD

**Issue by richsalz** [vasilvv/tls-alps#13]
Rather than have one extension value that uses two possible encodings, did you consider having three extensions -- call them application_settings_allowed, applications_settings_server, and applications_settings_client for lack of anything better?

**Comment by davidben** [comment]
Thanks for the feedback!

I don't think that would work due to the TLS solicited extensions rule. For the server to send an extension in EncryptedExtensions, the client must have sent that same code point in ClientHello. The draft does introduce client EncryptedExtensions, so we could have changed the rules, but aligning with the rest of TLS seems most natural.

It's pretty typical for TLS extensions to have different encodings between ClientHello and ServerHello/EncryptedExtensions/etc. The solicitedness rule all but requires it. (ALPN is the exception that proves the rule. It uses the same syntax, but it actually wasted bytes in doing so because the client extension offers a list of protocols, while the server extension selects a particular one.)

**Comment by richsalz** [comment]
How about making the data for the extension be a tagged union? I'm all for being able to look at a packet in isolation.

**Comment by davidben** [comment]
Well you already have a tag in the message header, so you can look at it in isolation (in so far as anything in TLS can be looked at in isolation; the ClientHello extension is the only cleartext one). Beyond that, that has not been what we typically do in TLS. See, e.g., key_share, pre_shared_key, supported_versions, and really just about every extension that appears in multiple messages. I'd rather stick to existing TLS convention here.

**Comment by richsalz** [comment]
i can live with it, thanks.
